### ISSUE TITLE
Hey there!

### ISSUE THREAD

**Issue by cvaliere** [Ilogeek/redmine_issue_dynamic_edit#1]
Hi

Nice plugin, I'm surprised that it didn't exist before: the only thing that I preferred in JIRA over Redmine!

just one comment about the style: I find it neater when the pencil is not displayed. I've overriden your CSS like this:
```
.value .dynamicEditSelect .selectedValue {
  display: none;
}
.value .dynamicEditSelect select {
  padding-right: 15px;
}
```
your choice of course, but it's neater

I noticed that it doesn't work on my installation for assignees, whereas I see it in your video demo

And do you think it would be hard to extend to all fields? Not only status, priority and assignee?

Thanks for the good work!

**Comment by Ilogeek** [comment]
Hi Colin,

Thank you for your issue and kind words.

As it's written in the `README`, you're free to edit the style and adjusts it to your need and your theme.

It's great that you find a way to customize it. If you need any more help about theming it don't hesitate to contact me or take a look at `issue_dynamic_edit.css` and `issue_dynamic_edit.js` files.

I can't find in my code where your problem about the assignee could come from. 
* Is the dropdown empty ?
* Is the field not updated after you've refreshed the page ?

(By the way, I just updated the code and use an other method to update issue's values. It now avoids conflict between revisions and it's not REST API dependant anymore)

I will take a look to add more fields (estimated time and % done at first)

**Comment by cvaliere** [comment]
I've found the problem with the assignee: I was the only user in my project, and I guess that your plugin does nothing if there is only one user

thank you for looking at other fields, will be great to have

**Comment by Ilogeek** [comment]
Hello Colin,

Last update give the ability to edit start date, due date, ratio and estimated time fields. I hope it will fulfill your expectations. It was tested on 3.4 version

**Comment by cvaliere** [comment]
Hello Hugo

Seems great!

Though, I just updated to latest version, and it fails:
```
ActionView::Template::Error (undefined local variable or method `userCanChangeStatus' for #<DetailsIssueHooks:0x0000000410aa28 @_routes=nil>):
    72:   end
    73: end %>
    74: <%= render_half_width_custom_fields_rows(@issue) %>
    75: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    76: </div>
    77:
    78: <% if @issue.description? || @issue.attachments.any? -%>
  plugins/redmine_issue_dynamic_edit/lib/details_issue_hooks.rb:29:in `view_issues_show_details_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:75:in `_app_views_issues_show_html_erb___761580398086963979_39032240'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Previous version was working well

Any clue?

**Comment by Ilogeek** [comment]
My bad ! A bad typo in the details_issue_hooks.rb file ...
A git pull with the last version should resolve the problem. Sorry for the inconvenience
