### ISSUE TITLE
Issue history didn't update after change some option

### ISSUE THREAD

**Issue by Mubat** [Ilogeek/redmine_issue_dynamic_edit#10]
Is it possible to update issue history after changing some option?

**Comment by Ilogeek** [comment]
Hello @Mubat 

Last commit add this new functionnality : 
- update the issue history list when an user modifies issue's attributes from plugin

Don't hesitate to contact me if you have any problem with the last update

**Comment by Mubat** [comment]
I checked and it's work fine.
