### ISSUE TITLE
		console.warn('Issue while trying to get version (avoiding conflict)');

### ISSUE THREAD

**Issue by ashrafalzyoud** [Ilogeek/redmine_issue_dynamic_edit#103]
![image](https://user-images.githubusercontent.com/50211455/211930305-ef399019-a5da-4d4d-ab19-8a192657b356.png)

**Comment by ashrafalzyoud** [comment]
@Ilogeek 
@Utopism 
@pflaeging 
@koledas

**Comment by Ilogeek** [comment]
Stop mentioning random people when you open all your issue without any info, any context and only paste partial part of your console error.
Don't forget to add sentences and (protips), it's better to use salutations when you speak with other people
