### ISSUE TITLE
broken description field 

### ISSUE THREAD

**Issue by crosspointst** [Ilogeek/redmine_issue_dynamic_edit#11]
My Redmine version is 3.3.3

After installing this plugin, The description field was broken below the capture.

![image](https://user-images.githubusercontent.com/16015254/30201201-cff056ac-94b4-11e7-9e4c-e42e5bca2a5d.png)

I guess this problem is this stylesheet. But I can't find a probrem point.

Thanks.

**Comment by Ilogeek** [comment]
Hello @crosspointst 

This is unfortunately theme dependant and i can't help you with that problem.

It seems that your sidebar has a fixed width value ( take a look at `id="sidebar"`). Maybe the title has in your sidebar theme has a fixed width.

Can you give me the name of your theme so i can try to reproduce your issue ?

**Comment by Ilogeek** [comment]
Hello @crosspointst 

I can't help you if you don't answer. Feel free to update and reopen this issue with the missing information and I'll help you to resolve your theme problem.
