### ISSUE TITLE
Automatic authorization in the API

### ISSUE THREAD

**Issue by vadimklochkov** [Ilogeek/redmine_issue_dynamic_edit#112]
The plugin is undoubtedly cool, but it requires additional authorization. Is it possible to disable this additional authorization so that the user does not enter the login password again after logging in? If not, will this be implemented in future versions?

**Comment by slykereven** [comment]
Are you talking about the popup authorisation server after login in redmine ?

**Comment by Ilogeek** [comment]
Hello @vadimklochkov 
This PR must do the trick : https://github.com/Ilogeek/redmine_issue_dynamic_edit/pull/108

**Comment by slykereven** [comment]
I use the fix #104 for few months now, so far so good :)
Should be merged i think !

**Comment by vadimklochkov** [comment]
Thx
