### ISSUE TITLE
Web auth keeps popping up in issue page

### ISSUE THREAD

**Issue by Raw1mage** [Ilogeek/redmine_issue_dynamic_edit#113]
When I view an issue at url such as https://mysite/issues/36, the web auth pops up.
![image](https://github.com/Ilogeek/redmine_issue_dynamic_edit/assets/40973866/1cdb351e-9d9d-48ac-9fd9-4a9071465a39)

I'm not sure if this is a bug or confliction with other plugins, but I tried two ways to cease the bugging:
1. pass the web auth 
2. Removing the redmine_issue_dynamic_Edit plugin.

Currently I am using some other plugins that might alter the Issue functions.
Will try them, too.
```
redmine_checklists
redmine_dmsf
easy_gantt_pro
```

There is not much log to investigate.  let me know if uploading anything could help.
```
I, [2023-08-28T05:57:00.814034 #1]  INFO -- : Started GET "/issues/36.json" for 1.34.74.47 at 2023-08-28 05:57:00 +0000
I, [2023-08-28T05:57:00.814568 #1]  INFO -- : Processing by IssuesController#show as JSON
I, [2023-08-28T05:57:00.814608 #1]  INFO -- :   Parameters: {"id"=>"36"}
I, [2023-08-28T05:57:00.844007 #1]  INFO -- :   Current user: anonymous
I, [2023-08-28T05:57:00.847334 #1]  INFO -- : Completed 401 Unauthorized in 33ms (ActiveRecord: 28.6ms | Allocations: 2685)

```

**Comment by slykereven** [comment]
Hi,
Try the fix https://github.com/Ilogeek/redmine_issue_dynamic_edit/issues/104
It should solve this problem

**Comment by Raw1mage** [comment]
Thanks.
Closing the issue now.
Expecting a merged release
