### ISSUE TITLE
Does no update 403

### ISSUE THREAD

**Issue by misiek303** [Ilogeek/redmine_issue_dynamic_edit#115]
Redmine

![Screenshot 2023-10-02 at 5 08 20 PM](https://github.com/Ilogeek/redmine_issue_dynamic_edit/assets/371344/6928945d-bcd5-4f88-aead-05cacaafc805)

![Screenshot 2023-10-02 at 5 13 16 PM](https://github.com/Ilogeek/redmine_issue_dynamic_edit/assets/371344/bd8c957f-93c8-47e6-b7da-f6cf5821e441)

```
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Classic
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.5
  redmine_budgets                1.0.4
  redmine_checklists             3.1.22
  redmine_cms                    1.2.4
  redmine_contacts               4.3.7
  redmine_drive                  1.2.0
  redmine_favorite_projects      2.1.3
  redmine_finance                2.1.8
  redmine_issue_dynamic_edit     0.9.1
  redmine_people                 1.6.3
  redmine_products               2.2.0
  redmine_questions              1.0.4
  redmine_resources              2.0.0
  redmine_theme_changer          0.6.0
  redmine_zenedit                2.0.5
```

**Comment by pkoevesdi** [comment]
I have the same problem, here's some more verbose console output:
![grafik](https://github.com/Ilogeek/redmine_issue_dynamic_edit/assets/33196971/7d923a1a-3a75-4cad-ad07-d405d71972b8)

**Comment by witcan** [comment]
> +1

Open redmine api
<img width="871" alt="image" src="https://github.com/Ilogeek/redmine_issue_dynamic_edit/assets/48895485/fab62104-4a55-49c1-ac5b-fbb112879678">

**Comment by Ilogeek** [comment]
Last commit f4f2862 may resolve the issue by disabling JSON Redmine API call
_(Do not hesitate to be as descriptive as possible (and constructive comments too) to help maintainers. PR are also open)_

**Comment by Ilogeek** [comment]
Look at your JS console you may see :
> [!CAUTION]
> Uncaught ReferenceError: nu is not defined

16519bb fix this issue (do not hesitate to check your JS console when having issue 👍)

**Comment by pkoevesdi** [comment]
> (do not hesitate to check your JS console when having issue 👍)

Yes, of course, sorry, missed that this time.
Finally, I see this plugin working on our site. Thank You very much, I appreciate Your work!
