### ISSUE TITLE
Not following "Field permissions" in workflow

### ISSUE THREAD

**Issue by ldrygiel** [Ilogeek/redmine_issue_dynamic_edit#12]
You can change a "read-only" field which after refresh returns to original value, but dynamic change is shown as accepted.

To reproduce:
Set "Read only" For "%Done" in "New" Status.
Create an issue (keep status as "New" for next steps)
If you edit it in classic way (via "Edit" link) there is no "%Done" field at all.
But if you view the issue page you can still edit "%Done" to any value dynamically and it shows OK for change, but if you refresh the page it goes back to 0%

**Comment by ldrygiel** [comment]
Same goes for adding a required field in 'next status' - dynamic change is shown as accepted but issue is not updated.
Plugin needs more testing in this area.

**Comment by Ilogeek** [comment]
Hello @ldrygiel 

Thank you for your comment. 

Last update tries to fix your issue : _Read only attributes can't be edited anymore._ 
If the status is updated ; edited fields are refreshed and old read only attributes can be modified if they're not in read only status anymore.

Don't hesitate to tell me if you find any problem with the update

**Comment by Ilogeek** [comment]
Hi @ldrygiel 

This update add a new constraint that would maybe resolve your problem : _user can't update status until all required field are filled_.

Feel free to give a feedback if it fits or not your need

**Comment by ldrygiel** [comment]
I updated the plugin. Warning message is good enough! Thanks for quick solution! I will feedback you if I find anything else. Plugin is very handy, speeds up maintaining issues a lot!
