### ISSUE TITLE
Ability to dynamically edit Title and description of the issue

### ISSUE THREAD

**Issue by vabue** [Ilogeek/redmine_issue_dynamic_edit#14]
Hi

Great work on the plugin, it brings extremely important feature for Redmine.

The ability to dynamically edit title and description also could be great in terms of usability. There is no need for any panel with icons, just pure text.

**Comment by Ilogeek** [comment]
Hello Valentine, 

Thank you for your kind words! 

The last commit adds the capacity to dynamically edit Issue's title. 
I'll try to add the description field as soon as possible.

Feel free to try this new version and come back to me if you find any mistake or problem :)

**Comment by Ilogeek** [comment]
Hello,

Description text is now editable. You can also use normal formatting text syntax (bold, italic ...).

If you find any bug don't hesitate to create an issue or comment this one and we will find a solution.

If you find the plugin helpful, please take a minute and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit
