### ISSUE TITLE
Can't use the previous/next button right over the issue subject

### ISSUE THREAD

**Issue by excceed** [Ilogeek/redmine_issue_dynamic_edit#15]
After I install this plugin, it bring great convince to me to update issues. But it come up with a little problem, the  **« Previous | 2 of 120 | Next »** link to previous or next issue cannot use any more.

Could you help to check if possible to fix this one.

Thanks @Ilogeek

**Comment by Ilogeek** [comment]
Hello @excceed 

Thank you for your message. It seemed that the title overrode the pagination. I updated the stylesheet and added `display:inline-block;` to the `h3` element : 

![Test](https://d26dzxoao6i3hh.cloudfront.net/items/1B3F0R2G2K3b230w1u1E/Screen%20Recording%202017-12-06%20at%2007.32%20PM.gif)

This may resolve your issue. Don't hesitate to come back if there's any problem with this fix or if you find any other issue.

If you find the plugin helpful, please take a minute and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by excceed** [comment]
@Ilogeek, Thanks for your quik response. it works~
