### ISSUE TITLE
No calendar icon display when second edit the date field start date or due date

### ISSUE THREAD

**Issue by excceed** [Ilogeek/redmine_issue_dynamic_edit#17]
Hello, @Ilogeek 
When I edit the start date, a box comes out with calendar icon, I can choose the exact date discover issue, this works well. 
![](https://raw.githubusercontent.com/excceed/TEMP/master/1.JPG)
But after I finished fill the start date and try to edit due date,  a box comes out WITHOUT calendar icon, I have to type 12/15/2017 manually, not by choose date in calendar.
![](https://raw.githubusercontent.com/excceed/TEMP/master/2.JPG)

**Comment by Ilogeek** [comment]
Hello @excceed

Thank you for your message. I didn't know Redmine had a datepicker fallback for browser that doesn't support date input.

I think that my last commit fixed your issue. 
If you find any mistake concerning this problem please come back here and we will find a way to fix it.

**Comment by excceed** [comment]
Thanks @Ilogeek You always come with quick answer. :)
It works~
