### ISSUE TITLE
Page doesn't get refreshed and gets stuck in the Loading process.

### ISSUE THREAD

**Issue by smoolya17** [Ilogeek/redmine_issue_dynamic_edit#18]
Hi @Ilogeek,

My redmine version: 3.4.3

When I try to edit any field, the field updates only when the page is refreshed after edit. The page load event needs to be added after each update or there seems to be some bug because when I edit the field 
the page shows 

> loading

and then doesn't display the updated page untill I refresh that page.

![image](https://user-images.githubusercontent.com/20811167/34452454-361940e8-ed65-11e7-9e48-d10daf1ac307.png)

Please look into its solution.

**Comment by Ilogeek** [comment]
Hi @smoolya17 

Could you please check your JS console from your web browser ( [HowTo](https://webmasters.stackexchange.com/a/77337) ) and try again to update a field. 

You'll see some information about what goes wrong. 

Could you copy / paste it here and expand all possible object (error data for example) so we can look if there's a problem with the ajax call the plugin performs to update the issue. Or if there's any JS error, paste it here that may help us a lot.

(Do you use the last version of the plugin ? Do you use other plugins ?)

I'm sure we will find a solution and make it works for you 👍

**Comment by Ilogeek** [comment]
Hello @smoolya17 

I can't do anything without data. Feel free to update and reopen this issue with the missing information and I'll help you to resolve your problem.

**Comment by aozhi2nd** [comment]
Meet the same issue, my  env 
```
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  additionals                    2.0.6
  advanced_roadmap               0.11.0
  projects_tree_view             0.0.9
  redmine__select2               1.1.0
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.0
  redmine_favourite_projects     0.9.1
  redmine_issue_badge            0.0.6
  redmine_issue_dynamic_edit     0.4.9
  redmine_issue_templates        0.1.8
  redmine_lightbox2              0.4.3
  redmine_per_project_formatting 0.0.4
  redmine_pivot_table            0.0.5
  redmine_questions              0.0.7
  redmine_stats                  0.0.1
  redmine_xlsx_format_issue_exporter 0.1.5
  sidebar_hide                   0.0.8
```
and the js console  from my web browser shows :
```
issue_dynamic_edit.js?1515399840:381 Uncaught ReferenceError: jsToolBar is not defined
    at initEditFieldListeners (issue_dynamic_edit.js?1515399840:381)
    at issue_dynamic_edit.js?1515399840:387
```

**Comment by aozhi2nd** [comment]
and another error 
```
Uncaught ReferenceError: jsToolBar is not defined
    at initEditFieldListeners (issue_dynamic_edit.js?1515399840:381)
    at Object.success (issue_dynamic_edit.js?1515399840:210)
    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:2)
    at x (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:4)
    at b (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:4)
    at Object.send (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:4)
    at Function.ajax (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js?1508097600:4)
    at issueDynamicUpdate (issue_dynamic_edit.js?1515399840:150)
    at HTMLSelectElement.<anonymous> (issue_dynamic_edit.js?1515399840:259)
```

**Comment by Ilogeek** [comment]
Hello @aozhi2nd 

Thank you for your help and your messages.
Thanks to them I was able to discover the problem and fixed it !

It seems that you use a plugin that add CKEDITOR to your textarea. 
I updated my plugin to make it works if you use the default textarea format or not (I also added the CKEDITOR support)

If you find any problem with this update don't hesitate to post it here and we will find a solution

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by aozhi2nd** [comment]
Great ! It works !
