### ISSUE TITLE
Enhancement to edit custom fields

### ISSUE THREAD

**Issue by waynerain** [Ilogeek/redmine_issue_dynamic_edit#19]
I like this plugin very much, however I am dealing with many custom fields in my issues.
Do you plan to add support for these, too?

**Comment by Ilogeek** [comment]
Hello @waynerain 

Thank you for your kind words. 

Custom fields don't have the same exact mechanism as regular fields we find foreach issue.
I've found a way to provide a support for custom fields. I need some times to provide a solution for each custom field type but I'm confident.

I will try to provide a new version next week with your request. 
I'll keep you updated on my progress

**Comment by Ilogeek** [comment]
Hello @waynerain 

Last update adds custom fields support. 
It's now possible to dynamically edit them like other issue's attributes. 
I don't use them a lot so don't hesitate to send me a feedback here if you find any issue concerning this last commit.

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by Ilogeek** [comment]
Hello @waynerain 

Don't hesitate to reopen this issue if you have any problem concerning your request.

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
