### ISSUE TITLE
issuse Edit status get JSeror

### ISSUE THREAD

**Issue by emiestas** [Ilogeek/redmine_issue_dynamic_edit#20]
in console:

jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4
issue_dynamic_edit.js:238  -------- Error while updating the issue attribute dynamically -------- 
issue_dynamic_edit.js:239  xhr data: 
issue_dynamic_edit.js:240 Object
issue_dynamic_edit.js:241  msg data: 
issue_dynamic_edit.js:242 error
issue_dynamic_edit.js:243  error data: 
issue_dynamic_edit.js:244 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://redmine.vilnius.lt/issues/bulk_update?back_url=%2Fissues%2F6735&amp;ids%5B%5D=6735&amp;issue%5Bstatus_id%5D=5'.
    at Object.send (https://redmine.vilnius.lt/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4:25549)
    at Function.ajax (https://redmine.vilnius.lt/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4:21302)
    at issueDynamicUpdate (https://redmine.vilnius.lt/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js:150:9)
    at HTMLSelectElement.<anonymous> (https://redmine.vilnius.lt/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js:259:3)
    at HTMLSelectElement.dispatch (https://redmine.vilnius.lt/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:8436)
    at HTMLSelectElement.r.handle (https://redmine.vilnius.lt/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:5139)
issue_dynamic_edit.js:245  ----------------------------------------------------------

**Comment by Ilogeek** [comment]
Hello @emiestas 

I tried to reproduce your problem with no success. It looks like you tried to change the status of the issue 6735. This procedure works well on my environment. We will try to figure out the problem together :

- Did you have this problem before or does it happen since your last plugin update ?
- Does the problem also appear when you update an other field ? (Priority, start or end dates, % done ...) Or it just happens when you update the issue status ?
- Is this status a specific one ? (Closing the issue for example ?) Does it trigger other actions such as moving the issue in an other project, deleting the issue ?
- Have you recently added an other plugin which can interfere on the issue Workflow ?

**Comment by emiestas** [comment]
This problem started after 0.4.7 (2017-12-04) this version 
also when edit status;prioritity date..
yes I have a lot of plugins maybe there are problem :(

![image](https://user-images.githubusercontent.com/7310362/35198142-0bead22e-fef3-11e7-8d55-7ca292926bb0.png)

![image](https://user-images.githubusercontent.com/7310362/35198168-9c5b7f0c-fef3-11e7-8f1e-26191ea4ba92.png)

**Comment by Ilogeek** [comment]
Hello @emiestas 

Great analysis on your side ! 

Is your Redmine configured to work on *http* or *https* protocol ? (In the Redmine settings : [http://www.redmine.org/projects/redmine/wiki/RedmineSettings](http://www.redmine.org/projects/redmine/wiki/RedmineSettings))
It may be a cross origin problem on your server ?

One trick we could try : [https://forum.jquery.com/topic/jquery-ajax-post-over-https-not-working](https://forum.jquery.com/topic/jquery-ajax-post-over-https-not-working)
> If you edit [issue_dynamic_edit.js](https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/master/assets/javascripts/issue_dynamic_edit.js#L155) at line 155, swtiching `async: false` to `async:true` ; does it resolve your issue ?

**Comment by emiestas** [comment]
issue_dynamic_edit.js So i try to change, but it doesn't fix bug. I rol back async: false.

What aoub in console this 
![image](https://user-images.githubusercontent.com/7310362/35299006-a0f6412e-008c-11e8-97f8-a7058a5786eb.png) it is your plugin error or no?

**Comment by Ilogeek** [comment]
Well it may be then a cross origin problem with the server configuration which results in not allowing AJAX call in https or something like that.

Concerning the JS error you raised, did you have this issue before you edited the file ? 
If we look at [issue_dynamic_edit.js:107](https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/2a10098d99b93c06514acc77d5c4de2fd5149c4e/assets/javascripts/issue_dynamic_edit.js#L107) it seems that `$('#required_field_array').html()` returns `undefined` in your case and then can't be properly parsed as a JSON string. I'll check for that to add a check on it. 

I'll keep you informed as soon as I commit a patch

**Comment by Ilogeek** [comment]
@timesong did a [great work](https://github.com/Ilogeek/redmine_issue_dynamic_edit/commit/97584b4a5bdfd90ad5ee59fae10700adcc5f1747) and fixed the JSON parse issue 👍

**Comment by emiestas** [comment]
So after update in 3.4. version  got another Error 
![image](https://user-images.githubusercontent.com/7310362/35667413-3c48528e-0736-11e8-8beb-87c4b0f3880e.png)

and I can't change the status it is not saved
![image](https://user-images.githubusercontent.com/7310362/35667498-908a659e-0736-11e8-95e9-33d9ef3c04c5.png)

![image](https://user-images.githubusercontent.com/7310362/35667511-9ccad05a-0736-11e8-9ae0-4d3af881f272.png)

**Comment by emiestas** [comment]
Ok, downgreid your version it works

**Comment by Ilogeek** [comment]
Hello @emiestas 

Thank you for your feedback. My last commit provides a fix for your JS issue ("outerHTML of undefined"). You can now upgrade to the last version and get the Custom Fields support.

I'm happy to see that you solved your server (and https requests) problem. May I ask you what was the solution for this issue ?

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍 Thank you for your help
