### ISSUE TITLE
bug: 414 Request-URI Too Long

### ISSUE THREAD

**Issue by ParisDakar** [Ilogeek/redmine_issue_dynamic_edit#22]
Hello.
After editing a field (for example 'description') with a lot of text 414 error appear.

> 414 Request-URI Too Long
> The requested URL's length exceeds the capacity
> limit for this server.

Plugin last commit is e74286667c3dc385a21816c27a557baaf519abc0
Plugin version | 0.6.1
Server | Apache/2.4.18 (Ubuntu)
Redmine | 3.2.3.stable
Ruby | 2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
Rails | 4.2.8
Database adapter | SQLite
User-Agent | Mozilla/5.0 (X11; Ubuntu; Linu…) Gecko/20100101 Firefox/58.0

**Comment by Ilogeek** [comment]
Hello @ParisDakar 

Thank you for your message. The last commit may resolve your problem. I edited the way I send the data and you won't get any 414 errors anymore.

Don't hesitate to send me a feedback here if you find any issue concerning this last commit.

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍 Thank you for your help

**Comment by Ilogeek** [comment]
Hello @ParisDakar 

Thank you for the help about your second issue.

I updated the JS code but I wasn't able to reproduce the problem (i tried with different browser without success, which one do you use ? Chrome, Firefox Quantum & Safari worked well). Do you use any specific Redmine plugin for your date inputs ?

Could you please upgrade to the last version and tell me if the last commit resolve your issue ?

**Comment by ParisDakar** [comment]
I use Firefox 58.0.2 on Ubuntu 16.04.3 LTS - as the client.
And Ubuntu 16.10 as the server.

There are plugins that I install:
* redhopper/
* redmine_hamster/
* redmine_issue_detailed_tabs_time/
* redmine_issue_dynamic_edit/
* redmine_user_specific_theme/
* scrum2b/

OK, this plugin collection is bad for test purposes. I remove *redhopper* and check your plugin again and bingo! No more "Loading..." after page is load.

@Ilogeek everything work fine!

**Comment by ParisDakar** [comment]
I'd like to close issue as completed well.

**Comment by Ilogeek** [comment]
Hello @ParisDakar thank you for your analysis.

I'll check the redhopper plugin if it may create conflict with my plugin.

I'm happy for you if everything works great !

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by ParisDakar** [comment]
> ...star it on Github and rate it 
Done!
