### ISSUE TITLE
Redmine. Error 404 - No route matches [GET] "/issues/304/quoted"

### ISSUE THREAD

**Issue by cubNguyen** [Ilogeek/redmine_issue_dynamic_edit#23]
After install this plugin, I can't use Quote (in Issue detail page), click but no response  
I open link of Quote to new tab, it show that: Redmine. Error 404 - No route matches [GET] "/issues/304/quoted"  
Please check this case, thanks !  

Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [i386-mingw32]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2

**Comment by Ilogeek** [comment]
Hello @cubNguyen 

Thank you for your message. I tried to use the quote button and everything works well : 

![Click on Quote button example](https://d2ffutrenqvap3.cloudfront.net/items/1v27060Q1P2Y0D3j2e2n/Screen%20Recording%202018-02-24%20at%2012.34%20AM.gif)

By clicking on the button, the page scrolls to the form at the bottom of the page and i can create a new note with a quote.

- Do you have any error that appears in your JS console when you click on the button ? 
- Do you have a specific plugin that can interact with quote ? (do you use other plugins that can create a conflict ?)
- Do you have the same issue with a 3.4.3 Redmine version ?

**Comment by Ilogeek** [comment]
Hello @cubNguyen 

Does your issue still occurs ? 
Is it possible to provide more info to reproduce your problem ? 
Does the problem disappear when you uninstall the plugin ?

Don't hesitate to post a comment here if you've found a solution
