### ISSUE TITLE
Enhancement to edit "Version"

### ISSUE THREAD

**Issue by pr0l** [Ilogeek/redmine_issue_dynamic_edit#24]
Hi.
Do you plan to add support for version?

**Comment by Ilogeek** [comment]
Hello @pr0l 

Thank you for your request. 
It looks like that **version field** works well when using **drop-down list** as **display** parameter in the field's options : 

![Example of my current config](https://dzwonsemrish7.cloudfront.net/items/023o1z0Z2A1Q0o2U1A35/%5B8cf9dd1721e2271e6a852f1e487a367a%5D_Image+2018-07-12+at+10.09.42+PM.png)

You should use this fix as a workaround until I can update the plugin. I'll try to find a way to make **checkboxes** display parameter works.

**Comment by Ilogeek** [comment]
Hello @pr0l 

I just updated the plugin. Version field with checkbox display is now supported.

If you find any problem with this update don't hesitate to post it here and we will find a solution

If you find the plugin helpful, please take a minute to star it on Github and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by pr0l** [comment]
@Ilogeek unfortunately the version field is not dynamic. This is the built-in redmine function. 
![2018-07-14 13 15 17](https://user-images.githubusercontent.com/39014797/42723535-4ffbcd44-8768-11e8-8941-4213fdda8d95.png)
![2018-07-14 13 13 01](https://user-images.githubusercontent.com/39014797/42723536-501d0c3e-8768-11e8-90af-e1f9dc564bfc.png)

**Comment by Ilogeek** [comment]
Hi @pr0l 

My bad, reading your request I thought you were speaking about custom field "*version*" (in *Administration* > *Custom fields* ).

The last update add the support for **Target version** and **Assignee** fields : 
![Example of the last update](https://dzwonsemrish7.cloudfront.net/items/0V1Q3M3M3B3J3k0i1a1J/Screen%20Recording%202018-07-15%20at%2011.01%20PM.gif)

Don't hesitate to come back here if it doesn't work as expected.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by pr0l** [comment]
everything works fine. Thank you very much for your work. For the plug-in to work completely, it needs to be reinstalled.
