### ISSUE TITLE
404 for /plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js

### ISSUE THREAD

**Issue by mfp20** [Ilogeek/redmine_issue_dynamic_edit#25]
And the issue is same of no plugin installed.

```
Started GET "/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js" for 192.168.1.34 at 2018-08-10 13:40:38 +0200

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js"):
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
  /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:9:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:18:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:120:in `call'
  /usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
  /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:113:in `call'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:518:in `call'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:165:in `call'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `public_send'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

**Comment by Ilogeek** [comment]
Be sure that the parent folder is called **redmine_issue_dynamic_edit**

Plugin path must be `/plugins/redmine_issue_dynamic_edit` then inside you should find `assets/javascripts/issue_dynamic_edit.js` (eg: /plugins/**redmine_issue_dynamic_edit**/assets/javascripts/issue_dynamic_edit.js)

>Do you have this structure in your plugin's folder ?

(Don't forget to restart your Redmine instance if you change the folder name)

Oh by the way : Hello ...

**Comment by mfp20** [comment]
@llogeek thanks for allocating some of your time for me. Unfortunately is not your plugin's problem. I just figured out a few minutes ago that all plugins' assets aren't copied in the {ROOT}/plugin_assets/ folder, and I've no idea why.
I firstly solved an [issue with fileutils 1.1.0](https://github.com/ruby/fileutils/issues/22), pinning and downgrading to 1.0.2. But it didn't change this one.

I'm pretty new to Redmine and RoR, I have no idea how to troubleshoot things. Do you have any tip for me?

**Comment by Ilogeek** [comment]
Hi @mfp20 

It looks like that your folder don't have writable permission or your environment configuration isn't set up properly :
- http://www.redmine.org/boards/3/topics/16126 (misconfiguration example)
- http://www.redmine.org/boards/3/topics/26452
- or maybe also https://github.com/pharmazone/redmine_charts2/issues/32#issuecomment-66696548

Did you follow the installation tutorial from Redmine website : http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions ?

Don't hesitate to post your issue on the Redmine forum to get help : https://www.redmine.org/projects/redmine/boards/2

**Comment by mfp20** [comment]
Yep, thanks for the links dude. Please, close this issue because isn't ... an issue (of your plugin).

Note for completeness sake: my RoR environment was a mess. The one installed with the OS package manager was obsolete so I had to find another install procedure, and I accidentally installed one using the sudoed root user ... it looks like it was picking some of both environments, or I was updating root's one but www-data's apache runtime was picking the system-wide one. Or alike.
I hate this tiny self-contained VMs backends ... developers have been too liberal in adopting those techs; it ended up having 4-5 full application stacks (RoR, python, nodejs, jvm, perl, php) clogging the memory and increasing complexity without a real need (as they all do the same thing, using a proprietary syntax).

I purged redmine/ruby/nodejs and started again, but the SD card got corrupted in the process and it is a remote system... just came back from the place were the SD needed an fsck, and moved the system to an usb HD to avoid flash corruption in the future.

Currently I have an rvm system-wide ruby install but I can't get www-data user pick it because apache doesn't run the /etc/profile.d/rvm.sh script. Anyway, I've already built libapache-passenger module using apxs, because using the OS package manager was pushing in the obsolete ruby version as a dependency of the libapache-passenger packaged binary module. Next step is try to add rvm.sh to /etc/apache/envvars in order to give the proper RoR envvars to the runtime env.

I wonder how the entire world is coping with RoR ... searching with google there are some questions about system-wide RoR instances but no answers; it seems like all the RoR apps running are poorly configured form a system administration perspective (ie: running as root, duplicate installs, long issue troubleshooting times). The most appreciated RoR installer (rbenv) doesn't even manage system-wide installs!
