### ISSUE TITLE
Request - Integration with Quick View plugin

### ISSUE THREAD

**Issue by Hasgassa** [Ilogeek/redmine_issue_dynamic_edit#26]
_I'm sorry but I don't know how to open a request, so I'm submitting an issue._

I really enjoy and use your plugin a lot, and I have an improvement idea for it, that would improve Redmine's productivity a lot.

Is it possible to make it to work with Quick View plugin, allowing to edit fields directly in the pop up window provided by Quick View plugin?

Thank you

**Comment by Ilogeek** [comment]
Hello @Hasgassa 

I'm happy you find the plugin helpful ! 

I've installed http://www.redmine.org/plugins/quick_view and updated `/plugins/quick_view/app/views/quick_view_issues/quick_view_issue_dialog.html.erb` file with [this content](https://gist.github.com/Ilogeek/e0b4da18397ee095adbebdd4b4046eab). The result is similar to (Display may change depending on your theme) : 
![Result](https://cl.ly/3Y1A0V0A2W0o/Screen%20Recording%202018-08-18%20at%2011.53%20AM.gif)

If this is the feature you want for your plugin here's how to add it : 
* Rename `/plugins/quick_view/app/views/quick_view_issues/quick_view_issue_dialog.html.erb` into something like `/plugins/quick_view/app/views/quick_view_issues/quick_view_issue_dialog.html.erb_old` (to rollback if my feature doesn't fit your need)
* Create again the file `/plugins/quick_view/app/views/quick_view_issues/quick_view_issue_dialog.html.erb` and paste my code into it : https://gist.github.com/Ilogeek/e0b4da18397ee095adbebdd4b4046eab
* Restart your Redmine instance
* You should have dynamic edit for the dialog window from the quick edit plugin !

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by Ilogeek** [comment]
Hello @Hasgassa 

Thank you for your feedback about the modification on `quick_view_issue_dialog.html.erb` I'm happy if it feets your need.

My plugin only supports regular fields and fields managed directly by Redmine (_custom fields_). I will install [Checklists](https://www.redmine.org/plugins/redmine_checklists) and try to find a way to support it if installed on the Redmine instance.

Your last request concerns Quick view plugin. I would suggest to contact directly the owner of the Quick View plugin. I don't own it and I'm not an expert so I think it's better if the modification is done by him. If you have IT skill don't hesitate to check its source code and discover how it works to implement it for Gantt plugin.

I'll come back to you after my tests with the Checklists plugin!

**Comment by Hasgassa** [comment]
Hello again @Ilogeek,

Thank you again for your efforts. It works now on the quick_view window!!! :)

As you mentioned, it's not working perfectly with this Checklists plugin, it has some limitations. For example, I've detected that when I tick a checklist checkbox, after that I cannot update a common field until I refresh issue's page, using quick_view or native issues window. It just starts hanging. Anyway, it's something I can live with, your plugin is great!!! 👍 

Answering to your question about the edited line, the line I've edited is not present anymore on your file. You may find it here: https://gist.github.com/Ilogeek/e0b4da18397ee095adbebdd4b4046eab/revisions#diff-bf10ee2a44be87f064d116ce7108bc14L84

**Comment by Ilogeek** [comment]
Hi @Hasgassa 

I've updated the plugin with a better way to support automatic updates (such as Checklists performs)
Feel free to install this new version and then update your Quick_View template with this new code : https://gist.github.com/Ilogeek/e0b4da18397ee095adbebdd4b4046eab (new variable at line 35)

Don't hesitate to come back here if you have any problem with this update 👍
