### ISSUE TITLE
При редактировании описания не подгружает в окно редактирования CKEditor plugin

### ISSUE THREAD

**Issue by sytkosa** [Ilogeek/redmine_issue_dynamic_edit#27]
При редактировании описания задачи не подгружает в окно редактирования CKEditor.

Т.е. 

![image](https://user-images.githubusercontent.com/10109949/44634316-d9477300-a9a0-11e8-9be5-539d85d792f9.png)

Если нажать предварительно редактировать что то изменить, а потом редактировать описание то окно будет таким
![image](https://user-images.githubusercontent.com/10109949/44634332-1f9cd200-a9a1-11e8-84fe-a24259338ef4.png)

Хотелось чтобы второе окно срабатывало всегда и отрабатывала логика нажатия кнопок

**Comment by Ilogeek** [comment]
Hi @sytkosa 

Thank you for your comment. Is it possible to write your messages in english ? It could be easier to understand for everybody here.

Unfortunately, I can't reproduce your issue. CKEditor launch the first time I click on the description field : 
![Working with CKEditor](https://dzwonsemrish7.cloudfront.net/items/023M2i0a0O1G1g251n3q/Screen%20Recording%202018-08-27%20at%2009.08%20PM.gif)

I've got : 
- Redmine 3.3.3
- Redmine CKEditor plugin 1.1.5 ( http://github.com/a-ono/redmine_ckeditor )
- Redmine Dynamic edit Issue plugin 0.6.4

Do you have any log in your JS console that appears when you have this problem ?

**Comment by sytkosa** [comment]
Hi
I have installed
![image](https://user-images.githubusercontent.com/10109949/44724351-14e65800-aadb-11e8-9bc0-173196244607.png)
Log
![image](https://user-images.githubusercontent.com/10109949/44724497-87573800-aadb-11e8-9ff2-067da0a36aba.png)

How to get error log ?
