### ISSUE TITLE
Conflict with ISSUE-id plugin

### ISSUE THREAD

**Issue by cyboman32** [Ilogeek/redmine_issue_dynamic_edit#29]
Redmine 3.4.x.

ISSUE-id plugin (https://www.redmine.org/plugins/issue_id) assumes that issue URL is like
issues/PROJECT-id

so
https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/master/lib/details_issue_hooks.rb
line 8
```
context[:request].original_url.rindex(/\/issues\/\d+/)
```
not matches, so plugin dosn't work.

Guess it should be
```
context[:request].original_url.rindex(/\/issues\/\S+/)
```
to fix that.

Thanks.

**Comment by Ilogeek** [comment]
Hello @cyboman32 

Thank you for your feedback! I've updated the plugin with your request and modified some variables in the JS file. Don't hesitate to install this new version and come back here if you have any issue.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
