### ISSUE TITLE
Redmine 3.4.1 - 500 error on version from 17/08/2017

### ISSUE THREAD

**Issue by Kerber0s** [Ilogeek/redmine_issue_dynamic_edit#3]
Completed 500 Internal Server Error in 419ms (ActiveRecord: 72.7ms)

ActionView::Template::Error (undefined local variable or method `userCanChangeStatus' for #<DetailsIssueHooks:0x8fbe738 @_routes=nil>):
    72:   end
    73: end %>
    74: <%= render_half_width_custom_fields_rows(@issue) %>
    75: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    76: </div>
    77: 
    78: <% if @issue.description? || @issue.attachments.any? -%>
  plugins/redmine_issue_dynamic_edit/lib/details_issue_hooks.rb:29:in `view_issues_show_details_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:75:in `_d2a7fe4a32eda7c9a191fa25c12bd6fb'
  plugins/advanced_roadmap/lib/advanced_roadmap/issues_controller_patch.rb:28:in `render'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'

**Comment by Ilogeek** [comment]
Hello Kerber0s, 

[Last commit](https://github.com/Ilogeek/redmine_issue_dynamic_edit/commit/4c76d1818243db55b4a4cd1c8067cffeba4e523a) performed yesterday fixed this issue. (Was also mentionned in #1 )

Did you get this update ? Have you restarted your Redmine instance ?
