### ISSUE TITLE
Assignee tab pencils

### ISSUE THREAD

**Issue by Geekul** [Ilogeek/redmine_issue_dynamic_edit#31]
After update to latest version i see 2 pencils on Assignee tab.
![image 001-2018-09-12](https://user-images.githubusercontent.com/15617788/45424978-bf947400-b6a0-11e8-8b92-f9908dd0dfd7.jpg)

**Comment by n0nag0n** [comment]
I see the same thing as well. It doesn't actually update anything, but then two pencils shows up for everything after I attempt to make an edit (with two loading icons, etc). It may be conflicting with a plugin, I haven't tried disabling plugins yet. I know it's not a theme issue as it does this on multiple themes as well.

**Comment by Ilogeek** [comment]
Hi, I've updated my Redmine instance to the last available version and made a fix for this issue.
Don't hesitate to reopen this ticket with your Redmine version if the problem still appears for you.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
