### ISSUE TITLE
Cant edit anything except title and description

### ISSUE THREAD

**Issue by LamtecUser** [Ilogeek/redmine_issue_dynamic_edit#34]
Cant edit anything except title and description.
![snippet](https://user-images.githubusercontent.com/28085023/47014273-09fa8c00-d14a-11e8-9288-32bb9399ad11.PNG)

**Comment by Anch9999** [comment]
Hi @LamtecUser 

Maybe you can try to use this way to fix it. [Issue#32](https://github.com/Ilogeek/redmine_issue_dynamic_edit/pull/33/commits/1223389806b9c72a402018852afe36ac722b3e8f)
I also occurred to this problem before, but now I can't reproduce this bug again.

**Comment by anatoly-kryzhanovsky** [comment]
some update - i can see that first problem is that there are issues with markup.
in my redmine (3.1.0 stable) table with issue info has following structure:
table (class attributes)
  tbody
    tr
      th (class status) Status:
      td  In Progress

but in js i see that you use following selector:  $('.details .attributes .status.attribute .value')
i try to fix this code and now i can see pencil icon on each field but no edit available (no js errors in console)...

**Comment by Ilogeek** [comment]
Hi,

Thank you for your feedback. We will try to find a solution for this issue but I need more info to help you with :
* Do you use any specific theme ? 
* Can you list all the plugins you have and the Redmine version ?
* Do you get any JS error in your browser developer console ( https://developers.google.com/web/tools/chrome-devtools/console/ ) ?
* Does the user who access the page has the correct settings to edit this field ? (Can he updates the issue by clicking on the "edit" link)

I'll try to reproduce the issue using markdown in the description of the Redmine issue
