### ISSUE TITLE
Middle clicking field with scroll wheel opens new tab, but also the edit box

### ISSUE THREAD

**Issue by owlnical** [Ilogeek/redmine_issue_dynamic_edit#36]
### Description

When clicking with the scroll wheel on a field which is also a link the edit box opens (e.g. the user name).

### Expected behaviour

This should only result in a new tab opening.

### Actual behaviour

A new tab opens *and* the edit box opens.

### Reproduce

1. Create new issue
2. Click with scroll wheel on user name

### Console output

None

### Client

- Debian Buster
- Firefox 63.0.3

### Server

- Ubuntu LTS 18_04

```
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               SQLite
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  collapsed_journals             0.0.3
  custom_menu                    1.8.3
  readme_at_repositories         0.3.0
  redmine_agile                  1.4.6
  redmine_base_deface            0.0.1
  redmine_base_stimulusjs        1.0.1
  redmine_checklists             3.1.11
  redmine_custom_css             0.1.7
  redmine_impersonate            1.0.0
  redmine_issue_dynamic_edit     0.6.3
  redmine_lightbox2              0.4.3
  redmine_messenger              1.0.2
  redmine_multiprojects_issue    3.4.5
  redmine_shady                  0.6.0
  usability                      2.3.3
```

**Comment by Ilogeek** [comment]
Hi @owlnical 

Thank you for the complete report. I've updated the plugin and the edit box will not be triggered if you click on a link anymore.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by owlnical** [comment]
Thanks for fixing the problem. I created an account and rated the gave the plugin a 5 star rating :)
