### ISSUE TITLE
JS Error on Redmine 3.4.7

### ISSUE THREAD

**Issue by Huangzc88** [Ilogeek/redmine_issue_dynamic_edit#37]
This error occurs when you create a new issue or In-line Click Edit：
![image](https://user-images.githubusercontent.com/31158857/50037881-8ed22b00-0051-11e9-87be-d9a804bdd3be.png)
![image](https://user-images.githubusercontent.com/31158857/50037902-f38d8580-0051-11e9-85b2-2ca00fe4081f.png)
![image](https://user-images.githubusercontent.com/31158857/50038005-7f53e180-0053-11e9-8468-8176d2ce9247.png)

System Info:
Environment:
  Redmine version                3.4.7.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    test
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.14
  Mercurial                      2.6.2
  Git                            1.8.3.1
  Filesystem

**Comment by Ilogeek** [comment]
Hi @Huangzc88 

The last plugin update resolves this issue. Sorry for the inconvenience and thank you for your feedback.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
