### ISSUE TITLE
i have dublicate button "assignet to"

### ISSUE THREAD

**Issue by juxta73** [Ilogeek/redmine_issue_dynamic_edit#38]
hi @Ilogeek. thank you for great work

i have dublicate not clickable edit icon "assignet to". any idea why this is happening? http://supps.ru/temp/bug1.gif

Environment:
  Redmine version                3.4.7.stable.17764
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  bestest_timer                  1.2.0
  redmine_banner                 0.1.2
  redmine_checklists             3.1.11
  redmine_ckeditor               1.1.5
  redmine_issue_badge            0.0.6
  redmine_issue_dynamic_edit     0.6.5
  redmine_lightbox2              0.4.3
  redmine_recurring_tasks        0.2.3

**Comment by Silex** [comment]
Same problem here.

**Comment by Tempris** [comment]
I added the following to my css styles in order to hide it for the time being (not a real permanent solution):

```css
body.controller-issues.action-show .assigned-to .value > .fa-pencil {
    display: none !important;
}
```

**Comment by Ilogeek** [comment]
Hi,

Thank you for your feedbacks. Sounds like the same issue as #31 and I've updated the plugin to avoid this kind of problem on the last Redmine version.
Don't hesitate to reopen this ticket if the issue still appears.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
