### ISSUE TITLE
Using  this plug-in with "Checklists plugin (Light version)"

### ISSUE THREAD

**Issue by Aymidas** [Ilogeek/redmine_issue_dynamic_edit#39]
First of all, Thanks of all,,

When I use this plug-in with Checklists plugin (Light version),
It has the little issue for editing the description. 
The 'enter' key mode can change to  "p" or "br" mode in Checklists plugin (Light version).
But, this plug-in supports only "p" mode.
How can I change the mode to 'br"  mode?

Thanks,

**Comment by Ilogeek** [comment]
Hello 

Thank you for your kind words ! 
I don't think if there's a solution for your specific case. Have you tried to press shift + enter (new line) instead of just enter (new paragraph) ?

Regards
