### ISSUE TITLE
configure field for no dynamic_edit

### ISSUE THREAD

**Issue by R-Glass** [Ilogeek/redmine_issue_dynamic_edit#41]
Hi, it would be a nice configuration feature if one could deselect some fields dynamic_edit ...
For example, no dynamic edit for the issue_description and comment text ...

thanks for your plugin ... I like it

**Comment by R-Glass** [comment]
Hi, it would be a nice configuration feature if one could deselect some fields dynamic_edit ...
For example, no dynamic edit for the issue_description and comment text ...

thanks for your plugin ... I like it

**Comment by Ilogeek** [comment]
Hi @R-Glass 

Thank you for your message. The last version of the plugin now includes a configuration file where you can exclude fields by their ID (css selector).
For your example you just have to edit `assets/javascripts/issue_dynamic_edit_configuration_file.js` at line 35 like that :
`var _CONF_EXCLUDED_FIELD_ID = ["DescriptionInput", "TitleInput"];`

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
