### ISSUE TITLE
using this plugin with "A common libraries"

### ISSUE THREAD

**Issue by antoninchadima** [Ilogeek/redmine_issue_dynamic_edit#42]
Hello, is there a way of using this plugin with http://rmplus.pro/ "A common libraries"

1. click on the pencil
2. edit the desired value
3. the new value is correctly displayed
4. **but the new value doesn't get stored**
5. reload the page
6. old value is shown

**Comment by antoninchadima** [comment]
I tried different settings for the used rmplus plugins without any result

**Comment by Ilogeek** [comment]
Hi @antoninchadima 

As mentionned in #28 by @dirmax , you can do the following : 

On the "_A common libs_" settings page on your Redmine instance administration (`settings/plugin/a_common_libs`) **uncheck the last element** that appears in Other setting (which is not translated). It's a setting named `enable_ajax_edit_form` in the code, "_Включить ajax загрузку формы редактирования задачи_" as current label (it's not translated in the plugin) :
<br/>

![Uncheck the last element](https://i.ibb.co/44c3473/Capture-d-e-cran-2019-04-14-a-23-08-36.png "Uncheck the last element")
You can then apply your modification. Hope it will help !

**Comment by antoninchadima** [comment]
thx
