### ISSUE TITLE
Issue with text fields

### ISSUE THREAD

**Issue by lublasco** [Ilogeek/redmine_issue_dynamic_edit#46]
Hi,

first of all congratulations for a nice plugin.

The plugin (last version) is working properly in my Redmine except for the **text** fields (default and custom fields). It shows the pencil and you can access the pop-up but just aren't able to change the value. The cursor disappears from the popup and you can't modify the text.

This happens with any theme and any Redmine version with different plugins. Do you know what can be causing this?

Thanks in advance for your help!

**Comment by Ilogeek** [comment]
Hi @lublasco 

Thank you for your kind words!

My last commit should have fixed your issue. Don't hesitate to come back on this ticket if you still encounter any problem.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by lublasco** [comment]
Hi, @Ilogeek, thank you too for your good opinion ;)

Your tweak works perfectly. Rating done ;)
