### ISSUE TITLE
Problem with redmine_wysiwyg_editor

### ISSUE THREAD

**Issue by skalimer0** [Ilogeek/redmine_issue_dynamic_edit#47]
Hello,

We use this plugin : https://www.redmine.org/plugins/redmine_wysiwyg_editor on redmine 4.0.3.

If I install your plugin, The TextArea for issue_descrptions and for issue_notes not working with this visual editor.

Otherwise, it's a good job, it's very useful to quickly modify issues.

Thanks.

**Comment by markusneg** [comment]
I can confirm this behavior on Redmine 4.0.4 with redmine_wysiwyg_editor 0.18.0

**Comment by Pabloanf** [comment]
I can confirm this issue on Redmine 4.1.1 with redmine_wysiwyg_editor 0.22.0

**Comment by skalimer0** [comment]
With REDMINE 4.2.4 and redmine_wysiwyg_editor 0.22.0 : no error

**Comment by SailorMan64** [comment]
I can confirm this is still an issue in Redmine 5.1.

- You can see and edit the Description when Markdown is selected.
- You cannot see the content when Visual Editor (WYSIWYG) is selected, but if you type in or past in content and Submit, it saves and shows correctly, but you still cannot see it if you click edit > Description again.
- The Preview does not work at all regardless of where content is typed/pasted.

Testing:
- I unchecked Enable JSONP support to see if it made a difference. - No go.
- I set var _CONF_FORCE_HTTPS = true; - No go.
- If I disable redmine_issue_dynamic_edit behavior of WYSIWYG editor is as expected.

Below are some screenshots of the Issue page and the error I could find in Chrome.

I love this plugin but I have to choose WYSIWYG editor over the convenience of dynamic edit of fields.

================================

![image](https://github.com/user-attachments/assets/5d301449-443b-445e-8c91-e6937a24862a)

![image](https://github.com/user-attachments/assets/f09ea033-89dd-49fb-834a-fb543b1dd339)

![image](https://github.com/user-attachments/assets/c7e3cc9f-a3b7-4910-9052-ee3c9bdec1fb)

Environment:
  Redmine version                5.1.3.stable.23143
  Ruby version                   3.1.6-p260 (2024-05-29) [x86_64-linux]
  Rails version                  6.1.7.9
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Next-level (includes JavaScript)
SCM:
  Subversion                     1.14.3
  Git                            2.43.0
  Filesystem                     
Redmine plugins:
  easy_gantt                     2.0
  easy_gantt_pro                 2.0
  easy_instant_messages          1.0
  next_level_bsc                 1.0
  next_level_customizations      1.0
  next_level_pyramid             1.0
  next_level_strategy_progress   1.0
  redmine_agile                  1.6.9
  redmine_blocks_layout          1.0
  redmine_checklists             3.1.25
  redmine_contacts               4.4.1
  redmine_drive                  1.2.1
  redmine_ics_export             5.0.0.dev
  redmine_issue_dynamic_edit     0.9.2
  redmine_issue_templates        1.2.1
  redmine_lightbox               1.0.2
  redmine_messenger              1.0.15
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.6.8
  redmine_questions              1.0.5
  redmine_recurring_tasks        0.3.4
  redmine_reporter               2.0.4
  redmine_resources              2.0.3
  redmine_spent_time             4.1.0
  redmine_translation_terms      5.1.0
  redmine_wysiwyg_editor         0.33.0
  redmine_xapian                 3.0.7
  redmine_zenedit                2.0.6
  redmineup_tags                 2.0.14
