### ISSUE TITLE
Quotes break plugin work

### ISSUE THREAD

**Issue by ViktarZakharau** [Ilogeek/redmine_issue_dynamic_edit#49]
If there are quotes in the title, then the entire title is not displayed when editing.

![error](https://user-images.githubusercontent.com/52623843/60767135-dab2f300-a0bb-11e9-8fe4-b544954f92f7.png)

**Comment by Ilogeek** [comment]
Hi @ViktarZakharau 

This issue was resolved by @pflaeging thanks to its commit!
If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
