### ISSUE TITLE
Unexpected format on issue detail page

### ISSUE THREAD

**Issue by Mubat** [Ilogeek/redmine_issue_dynamic_edit#5]
We have an another result of using plugin.
Plugin version: 0.3.0

On custom (_Hardpixel_) layout:
![screenshot from 2017-08-19 11-20-01](https://user-images.githubusercontent.com/3623986/29484864-87e6a0ee-84d0-11e7-9991-73a83489ceeb.png)

On default (_Classic_) layout:
![screenshot from 2017-08-19 11-20-37](https://user-images.githubusercontent.com/3623986/29484867-95ffe8e8-84d0-11e7-89e4-205b44a1975b.png)

**Comment by Ilogeek** [comment]
Hello Mubat,

Edit fields are correctly created and inserted but it seems that JS and CSS files from the `assets` directory aren't loaded. This 2 files give the aspect and move fields to their correct places.

In the source code of the page, do you have any mention of `issue_dynamic_edit.css`and `issue_dynamic_edit.js` ? (eg : `<link rel="stylesheet" media="screen" href="/plugin_assets/redmine_issue_dynamic_edit/stylesheets/issue_dynamic_edit.css" />`at top of the page and `<script src="/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js"></script>` just before the `body` closing tag ?) If you have them, do they exist on your server or does it give you a 404 error ?

Is there any JS error in the Javascript console of your browser ?

**Comment by TrumanRu** [comment]
Maybe would be enough to press Ctrl+F5 to reload cached page.

**Comment by Mubat** [comment]
Problem resolved.
I had clone plugin to folder named `issue_dynamic_edit`, and plugin has hard web path to assets.
