### ISSUE TITLE
Checkbox input not working correctly with List or Key/value list

### ISSUE THREAD

**Issue by simonarthur** [Ilogeek/redmine_issue_dynamic_edit#53]
When I have a custom field with a List type or "Key/value list" type, "Checkbox" input, and  the input control that shows up is not correct. Instead of showing a list of values with checkboxes beside them, this plugin instead shows a single checkbox in the pop-up, with no values listed.

**Comment by Ilogeek** [comment]
Hello @simonarthur 

Thank you for your feedback. I've updated the plugin and it now correctly handles checkboxes.
Feel free to install the v.0.6.8 and don't hesitate to come back to me if you have any difficulties with this update.
