### ISSUE TITLE
dynamic category change does not work

### ISSUE THREAD

**Issue by pr0l** [Ilogeek/redmine_issue_dynamic_edit#54]
Good afternoon, dynamic category change does not work.

Redmine version                         3.4.12.stable
Ruby version                               2.4.9-p362 (2019-10-02) [x86_64-linux]
Rails version                                4.2.11.1
redmine_issue_dynamic_edit     0.6.8

**Comment by Ilogeek** [comment]
Hi @pr0l 

Category field wasn't supported before. Last update fix this issue and you'll be able to update your redmine issue's category.

If you find the plugin helpful, take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Comment by pr0l** [comment]
everything is super, checked it works great. Thank you so much
