### ISSUE TITLE
all categories of redmine are shown

### ISSUE THREAD

**Issue by pr0l** [Ilogeek/redmine_issue_dynamic_edit#55]
Dynamic category change includes all categories from all redmine. Most likely they will not check whether the categories belong to the project.

`dynamic field`
![image](https://user-images.githubusercontent.com/39014797/68844885-ca92cc00-06ca-11ea-962e-444b0de087c4.png)
`field when editing`
![image](https://user-images.githubusercontent.com/39014797/68844957-f0b86c00-06ca-11ea-85ad-480c807c81e3.png)

**Comment by Ilogeek** [comment]
Hi @pr0l 

I've updated the project and Categories are now filtered by project.
You may update your version of the plugin to get the wanted result.

Please support this plugin and take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
