### ISSUE TITLE
_CONF_FORCE_HTTPS could not force from HTTP to HTTPS

### ISSUE THREAD

**Issue by tqvinh0510** [Ilogeek/redmine_issue_dynamic_edit#56]
Hi guys,
I installed this lib, but when I use SSL for my REDMINE and change option _CONF_FORCE_HTTPS to "true" then AJAX could not force to HTTPS.
Image for this problem: https://imgur.com/Tjj4uv0

Please fix this issue. Thank you for your hard-working.

**Comment by Ilogeek** [comment]
Hello @tqvinh0510 

Thank you for your message. Unfortunately this kind of issue is probably a misconfiguration of the server and the http to https redirection and even if the plugin call the URL with an https link, your server redirect it to an insecure version of the page.
You can inspect your network activity when you edit a field ( https://developers.google.com/web/tools/chrome-devtools/network ) to check how your server redirects requests.

You can also check this issue https://github.com/Ilogeek/redmine_issue_dynamic_edit/issues/35
