### ISSUE TITLE
input field closes after next click, when using _CONF_LISTENER_TARGET = "fa_pencil";

### ISSUE THREAD

**Issue by volcom** [Ilogeek/redmine_issue_dynamic_edit#59]
First of all:
We like this extension very much!
We want tu use fa-pencil as listener!
When activated, the first clik on the pencil opens the dialog -> good,
next click (f.e. in the dialogs textfield or on a button) closes the original dialog. So we can not update any value.
When setting back to _CONF_LISTENER_TARGET = "value" everything works as expected.

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.1
  redmine_checklists             3.1.16
  redmine_cms                    1.2.1
  redmine_contacts               4.2.6
  redmine_contacts_helpdesk      4.1.6
  redmine_issue_dynamic_edit     0.6.9
  timelog_timer                  2.0.0
  view_customize                 2.1.0

**Comment by Ilogeek** [comment]
Hi @volcom 

Thank you for your kind words! 
I've done a recent update trying to fix the issue you mentionned.
Feel free to try this new version and come back to me if you still encounter some difficulties.

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit Thank you very much 👍
