### ISSUE TITLE
Field value update doesn't care about required custom fields

### ISSUE THREAD

**Issue by TrumanRu** [Ilogeek/redmine_issue_dynamic_edit#6]
If custom field flag 'Required' is active users can't save edited issue till he fill this field's value.

This plugin gives users workaround to change any editable value without filling required fields.

**Comment by ldrygiel** [comment]
More of doesn't look at Workflow / Fields permissions tables. 
My example: 
Set "Read only" For "%Done" in "New" Status.
Create an issue
If you edit it in classic way (via "Edit" link) there is no "%Done" field at all.
But if you view the issue page you can still edit "%Done" to any value dynamically and it shows OK for change, but if you refresh the page it goes back to 0%
This will get people confused.

**Comment by Ilogeek** [comment]
Hello @TrumanRu 

I updated the plugin and the last commit add a new constraint that would maybe resolve your problem : _user can't update status until all required field are filled_.

Feel free to give a feedback if it fits or not your need
