### ISSUE TITLE
bug in mobile version of issue page

### ISSUE THREAD

**Issue by Deamount** [Ilogeek/redmine_issue_dynamic_edit#60]
Hi. There are bug in mobile version of site in issue page. Menu takes up half of the screen.
redmine 3.4.4, ruby 2.5.1, Rails 4.2.10, your plugin 0.6.8

**Comment by Deamount** [comment]
![WhatsApp Image 2020-03-03 at 14 36 54](https://user-images.githubusercontent.com/61799188/75912523-6a36be80-5e62-11ea-8b4d-6ae403f11848.jpeg)

 Menu never closes, when plugin installed.

**Comment by Ilogeek** [comment]
Hi @Deamount 

I can't reproduce your issue. Are you sure it's not a problem with your theme or an other plugin that may interfere with your menu?

Here is how my menu works with my plugin activated : 
![Responsive menu doesn't have any conflict](https://d1sz9tkli0lfjq.cloudfront.net/items/241m1Y3C20190J2R0D2V/Screen%20Recording%202020-03-14%20at%2006.34%20PM.gif)

Don't hesitate to come back with more info.
