### ISSUE TITLE
HTML tags hierarchy was screwed up

### ISSUE THREAD

**Issue by xoox** [Ilogeek/redmine_issue_dynamic_edit#61]
Hi, thanks for this great plug-in. My problem is that the HTML tags hierarchy was screwed up when using this plugin.

### System information:

```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
Redmine plugins:
  progressive_projects_list      4.0.0
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_issue_templates        1.0.1
  redmineup_tags                 2.0.8
  redmine_issue_dynamic_edit <The latest master branch>
```

### How to reproduce

1. Without redmine_issue_dynamic_edit, browse an issue detail page without signing-in. Press "F12" in a Chromium compatible browser to show the developer tools. In the "Elements", check the HTML tree. We'll see that `<div id="history">` and `<div id="other-formats">` are both child nodes of `<div id="content">`.
![good](https://user-images.githubusercontent.com/1014277/78095445-8f8afe00-7409-11ea-9739-2065a454cb51.png)

2. Install redmine_issue_dynamic_edit, use the same above method to inspect the "Elements" of HTML source. Now the `<div id="history">` and `<div id="other-formats">` are both child nodes of `<div id="main">` and sisters of `<div id="content">`.
![bad](https://user-images.githubusercontent.com/1014277/78095628-fe685700-7409-11ea-8713-bd02fb3e486e.png)

Could you please have a check and fix it? Thanks.

**Comment by Ilogeek** [comment]
Hi @xoox 
Thank you for your message and raising this issue!

Unfortunately, I wasn't able to reproduce your problem. Can you please provide more info :
- Do you use a specific Redmine theme ?
- Do you still have this issue if you disable all your other plugins ? (trying to discover if there's a conflict with redmine_checklists or redmine_issue_template for example)

**Comment by xoox** [comment]
Good. Problem solved.
Thanks for your help and this charming work.
