### ISSUE TITLE
Broken CSS when user has no 'Edit Issues' permission

### ISSUE THREAD

**Issue by axellerater** [Ilogeek/redmine_issue_dynamic_edit#64]
With the plugin activated, log in on an user that has no permission to edit issues, only view.

Steps:

1. Create user
2. Assign Group to user that has no Edit Issues permission in the Permission Report
3. View an issue created by someone else

**Comment by Ilogeek** [comment]
"**Hello**"

Last commit should fix your issue

"**You're welcome. Have a good day too**"

> Please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit
