### ISSUE TITLE
Available statuses are not reloaded after status change

### ISSUE THREAD

**Issue by TrumanRu** [Ilogeek/redmine_issue_dynamic_edit#7]
'Workflow - Status transitions' configuration doesn't allow to change from status 'In Progress' to status 'Resolved'. Status 'Resolved' only available from status 'Testing'.

After status changed from 'In Progress' to 'Testing' status 'Resolved' still unavailable.
Refreshing page shows correct statuses for choice.

**Comment by Ilogeek** [comment]
Hello @TrumanRu 

Last update fixed this enhancement. After the AJAX call, we use the returned page value to update the status dropdown list ( https://github.com/Ilogeek/redmine_issue_dynamic_edit/commit/efe0d790651fddc1e8fafdd5bb3e7844176e223e#diff-96bb972d1dd0a7bda840ba8234dd84be ) 

Don't hesitate to update this issue if you find any problem
