### ISSUE TITLE
Plugin revert changes made by other user while your page was open

### ISSUE THREAD

**Issue by f0mster** [Ilogeek/redmine_issue_dynamic_edit#70]
1) Open task
2) Open same task in other window and change some fields
3) From first window change field.
All fields changed in windows 2 will be reverted.

**Comment by Ilogeek** [comment]
Fixed with last update and `_CONF_CHECK_ISSUE_UPDATE_CONFLICT` new variable

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
