### ISSUE TITLE
feature requests: Intranet deployment, do not use CDN

### ISSUE THREAD

**Issue by tianyang-abc** [Ilogeek/redmine_issue_dynamic_edit#74]
Hi, it's a great plugin. Max efficient.
But our servers are in Intranet. Users cannot link to Internet for **font-awesome.min.css**. 😞

**Comment by Ilogeek** [comment]
Hi @tianyang-abc !
Thank you very much for your kind words.
I'm working on a new rewamped version of the plugin and i'm dropping font-awesome to avoid this kind of scenario.
I'll let you know when this new version will be available (maybe in a week or two)
Best regards

**Comment by Ilogeek** [comment]
Hi @tianyang-abc 

Last update fixed your request. FontAwesome is not used anymore and no external files are loaded.

Don't hesitate to reopen this issue if you have difficulties with the fix.

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
