### ISSUE TITLE
Display failure in Ticket Details

### ISSUE THREAD

**Issue by kermitDerFrosch** [Ilogeek/redmine_issue_dynamic_edit#79]
Hello,

After adding this nice plugin in a fresh redmine installation, the ticket details are misaligned. it looks like this: ![fresh_plugin_installation](https://user-images.githubusercontent.com/25843942/112753675-df7ab180-8fd8-11eb-9fb9-7585d0ea8654.png)

In the css the .splitcontent container is set to "display: table-row" which breaks the layout.
To solve it i deleted line this rule. You find it on **line 118 in redmine_issue_dynamic_edit/assets/stylesheets/issue_dynamic_edit.css** 

After changing this, it looks like we want.

![after_css_fix](https://user-images.githubusercontent.com/25843942/112753671-dee21b00-8fd8-11eb-9918-aea5f392401c.png)

Best regards
Kermit

**Comment by Ilogeek** [comment]
Hi @kermitDerFrosch 

Thank you very much for the fix, I added it into the last update

Don't hesitate to reopen this issue if you have any question about this CSS bug

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
