### ISSUE TITLE
doesn't show error message when Custom Workflow plugin stops save in 'Saving observable objects' procedure

### ISSUE THREAD

**Issue by TrumanRu** [Ilogeek/redmine_issue_dynamic_edit#8]
Refresh page restores all previous field values. This means that AJAX save was unsuccessfull.

**Comment by Ilogeek** [comment]
Hello TrumanRu,

I've recently updated the plugin with some of your issues. Last commit concerns this specific one : If the AJAX request was unsuccessful an error message appears and the details display all previous values.

Tell me if it works well for you and don't hesitate to update your comment on http://www.redmine.org/plugins/redmine_issue_dynamic_edit if you find the plugin helpful. Thank you for your help !
