### ISSUE TITLE
Cannot read property 'getData' of undefined at initEditFieldListeners

### ISSUE THREAD

**Issue by Paladin47** [Ilogeek/redmine_issue_dynamic_edit#85]
Hello!
First, thanks for this great plugin!
It really helpful for fast editing issues.

But I have this problem with CKEDITOR plugin.
When I just opening any issue in Redmine, I receiving this error in JS console:
![image](https://user-images.githubusercontent.com/88137223/127464026-f21af39b-437d-424d-be13-6e8137ee8c30.png)

![image](https://user-images.githubusercontent.com/88137223/127464117-5d9699e6-2c2e-4e7a-b8b5-34f7758db487.png)

And dynamic edit of custom fields doesn't work. :(
I click on the field, select a different value, click Apply and nothing happens.

My configuration:
Environment:
  Redmine version                3.4.10.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.3
  custom_menu                    1.8.6
  global_roles                   2.2.4
  luxury_buttons                 4.1.0
  once_assigned_ever_watcher     1.0.0
  redmine_base_deface            1.3.2
  redmine_ckeditor               1.1.7
  redmine_default_custom_query   1.3.0
  redmine_email_fetcher          0.3.1
  redmine_extended_watchers      1.0.5
  redmine_gemavatar              1.1
  redmine_helpdesk               0.0.15
  redmine_issue_dynamic_edit     0.7.2
  redmine_issue_status_colors    0.0.1
  redmine_issue_tabs             1.3.2
  redmine_ldap_sync              2.1.1.devel
  redmine_lightbox2              0.4.4
  redmine_per_project_formatting 0.0.5
  redmine_per_tracker_categories 1.0.0
  redmine_sender                 1.4.8
  redmine_silencer               0.4.3
  redmine_stealth                0.7.2
  redmine_touch                  0.0.3
  redmine_watchers_groups        1.0.0
  unread_issues                  2.2.3
  usability                      2.3.9

**Comment by Ilogeek** [comment]
Hi @Paladin47 

Thank you very much for your kind words
Last update resolved this issue

Don't hesitate to reopen this issue if you have difficulties with the fix.

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
