### ISSUE TITLE
Issue details jump to the left every time you tap on an issue with a mobile phone

### ISSUE THREAD

**Issue by msundin** [Ilogeek/redmine_issue_dynamic_edit#87]
When viewing details of an issue, i.e. tapping on an existing issue/issue number, on a mobile phone (at least on an Android phone), the issue details jumps to the left so you have to swipe to the left to center the content every time you open an issue's details. The root cause seems to be that a large empty area is created to the right of the content. I.e. it is possible to swipe a long way to the right where there is content, just empty space.

- Tested with the same result with the following browsers on Android phone: Chrome, Brave, "Samsung Internet".
- Using Redmine 4.2.2
- No issue if for the above scenario on a laptop using e.g. Chrome or Brave browser
- Probably an issue with the responsiveness of the webpage that this plugin affets. I.e. show up on mobile device but not on a laptop.

Steps to reproduce:
- Install "Redmine issue dynamic edit": The issue starts appearing in the scenario explained above.
- Uninstall "Redmine issue dynamic edit": The issue disappears"

Tested to install and uninstall "Redmine issue dynamic edit" several times to be sure that this plugin is causing the issue.

**Comment by Ilogeek** [comment]
Hi @msundin 

Last update resolved this issue. 
Input now appears below its initial value on small screens

Don't hesitate to reopen this issue if you have difficulties with the fix.

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
