### ISSUE TITLE
Co-editing a task at the same time 

### ISSUE THREAD

**Issue by 6el-i** [Ilogeek/redmine_issue_dynamic_edit#88]
Hi! First of all, let me thank you for this wonderful plugin!!!
I have a question.
I opened the page and view the task, my colleague edited it from his computer, I change the status of the task using the plugin, all changes made by my colleague are erased. Is it possible to enable checking, not apply changes if the task was edited while I was viewing it. Since this is implemented through the standard editor

![giffff](https://user-images.githubusercontent.com/78407747/138674681-e3d2a9b9-9451-4949-bd67-631e6597ead2.gif)

**Comment by Ilogeek** [comment]
Hi @6el-i 

Thank you for the complete description and your kind words!

Last version default behavior was : updating issue with the plugin overrides all modifications already made
With last update and new variable `_CONF_CHECK_ISSUE_UPDATE_CONFLICT` user will not be able to override modification performed while he was viewing the issue. User will have to refresh the page or use the dedicated button to refresh the data. Specific message will be displayed automatically to inform the user about modifications from other users.

Don't hesitate to reopen this issue if you have difficulties with the fix.

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
