### ISSUE TITLE
Suppress updates while text fields are active

### ISSUE THREAD

**Issue by korla-plankton** [Ilogeek/redmine_issue_dynamic_edit#89]
It appears that, with this plugin enabled, Redmine performs a GET on the issue every ~5 seconds. If you happen to be editing a text field while this happens, characters can be 'dropped', leading to typos.
Would it be possible to suppress those GETs when a text input field is active?

I'm using the latest Redmine docker image (4.2.3) and version 0.8.0 of the plugin. No other plugins are installed.

**Comment by Ilogeek** [comment]
Hi @korla-plankton 

Thank you for the feedback. This GET call is performed to check if any update has been made on the issue while editing it (avoiding conflict and modification erasure)

I've found the problem causing random laggy input delay. 
Into [issue_dynamic_edit.js (L209)](https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/master/assets/javascripts/issue_dynamic_edit.js#L209) you have to remove the parameter `async : false,` and instead set `global : false,`

Second possibility is to update [issue_dynamic_edit_configuration_file.js (L60)](https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/master/assets/javascripts/issue_dynamic_edit_configuration_file.js#L60) to set this option to `false` (as described into the README and last commit ...). It will prevent repetitive AJAX calls and conflict check while editing your issue

I will commit the fix tomorrow

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍

**Comment by korla-plankton** [comment]
Sorry for the delayed response. Thank you for the update, the latest version is working well. And thank you for this very useful plugin!
