### ISSUE TITLE
0.8.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [Ilogeek/redmine_issue_dynamic_edit#91]
Thx for your plugin 
Can u tell me what error and how I can fix it

**Comment by ashrafalzyoud** [comment]
![image](https://user-images.githubusercontent.com/50211455/150847789-8198ba50-4853-480e-9ef6-c2ec3995c3c0.jpeg)

**Comment by Ilogeek** [comment]
Hi @ashrafalzyoud 

Thank you for opening this issue

It looks like you resolved it by yourself.
Could you explain the solution you applied to your issue ? 
It could help other people having the same JS error.

**Comment by ashrafalzyoud** [comment]
Update chorme version up 95
