### ISSUE TITLE
Redmine WYSIWYG Editor compatibility

### ISSUE THREAD

**Issue by alterdaemon** [Ilogeek/redmine_issue_dynamic_edit#98]
- wisiwyg preview doesn't work
- wisiwyg editor occasionaly doesn't load

repo link:
https://github.com/taqueci/redmine_wysiwyg_editor/network

**Comment by pr-dtakac** [comment]
I think I found the bug. After my changes it's finally working. I also made small change in css, because when I for example have some bigger image in issue description, after switching to preview in dynamic edit modal position of this modal was bad (toolbar wasn't visible).

@Ilogeek can you check this and add similar fix in next release?
```diff
--- a/assets/javascripts/issue_dynamic_edit.js
+++ b/assets/javascripts/issue_dynamic_edit.js
@@ -151,7 +151,7 @@ var cloneEditForm = function(){
                        cfg.height = 100;
                        CKEDITOR.replace("issue_description_dynamic", cfg)
                }else if (typeof(jsToolBar) === typeof(Function)) {
-                       var wikiToolbar = new jsToolBar(document.getElementById('issue_description_dynamic')); wikiToolbar.draw();
+                       var wikiToolbar = new jsToolBar(document.getElementById('issue_description_dynamic')); wikiToolbar.setPreviewUrl('/preview/text'); wikiToolbar.draw();
                }
        }
 
--- a/assets/stylesheets/issue_dynamic_edit.css
+++ b/assets/stylesheets/issue_dynamic_edit.css
@@ -56,7 +56,8 @@ body.controller-issues.action-show .dynamicEditField {
        opacity: 0;
        transition: opacity .3s ease-in;
        /* left:0; correct position on top of icon */
-       bottom: 100%;
+       /*bottom: 100%;*/
+       top: 10%;
        margin-bottom: 5px;
        box-sizing: border-box;
        padding: 10px;
```

**Comment by Ilogeek** [comment]
Hello @pr-dtakac 

Thank you for your feedback and investigation
This issue may have the same problem : https://github.com/Ilogeek/redmine_issue_dynamic_edit/issues/100 and my last commit may have solved it

Don't hesitate to come back to me if you have any difficulty 

If you find the plugin helpful, take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
